# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1dab1a8bec862e5edd996178c244e37808b3f62e8df7bb481eeabfab8a610715648d159731416548be035b3730614e72b156cc5536149c3f4955a9fb41ddd91

test:
  secret_key_base: 7053a8b176078ad4145e7798343d950393501724430fc90fee56a2634611368da41373be2e0f7c089bf79afc45e24f9b82c61b69d8d1bb4962d4ac2e243a14b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
